server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  h2:
    console:
      enabled: true
  application:
    name: demo-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
