server:
  port: 8080
spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  application:
    name: demo-web
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
eureka:
  client:
    service-url:
          defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include:
          - env
          - refresh
          - health
  endpoint:
    health:
     show-details: always
  health:
    defaults:
      enabled: false
#demo-service:
#      ribbon:
#        ReadTimeout: 3000
logging:
  level:
      issac.study.springdemo: debug

mro:
       websocket:
                 enable: true