server:
  port: 8080
spring:
  application:
    name: demo-web
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
eureka:
  client:
    service-url:
          defaultZone: http://localhost:8761/eureka/

