server:
  port: 8888
spring:
  application:
    name: demo-config
  cloud:
    config:
        server:
           native:
            search-locations: file:/D:/mycode/config/
  profiles:
    active: native

eureka:
  client:
    service-url:
          defaultZone: http://localhost:8761/eureka/

